"""Public domain models used by the API and map compiler."""

from .editor import (
    APIModel,
    AnnotationCollection,
    BlackBoxEntity,
    CandidateBox,
    DoorEntity,
    EditorProject,
    EditorSettings,
    EntityCollection,
    InitialFire,
    MapDescriptor,
    MapEntity,
    PlacementReport,
    Point,
    ProjectDerived,
    SimulationSettings,
    Stroke,
    StrokeLayers,
    ValidationIssue,
    ValidationResult,
)

__all__ = [
    "APIModel",
    "AnnotationCollection",
    "BlackBoxEntity",
    "CandidateBox",
    "DoorEntity",
    "EditorProject",
    "EditorSettings",
    "EntityCollection",
    "InitialFire",
    "MapDescriptor",
    "MapEntity",
    "PlacementReport",
    "Point",
    "ProjectDerived",
    "SimulationSettings",
    "Stroke",
    "StrokeLayers",
    "ValidationIssue",
    "ValidationResult",
]
